server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/script_generator?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  application:
    name: script-generator
    
  # WebSocket配置
  websocket:
    enabled: true
    
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# 阿里通义千问配置
dashscope:
  api:
    key: sk-b551605ddd164c9990ac784ad013b472
  model:
    name: qwen-turbo

logging:
  level:
    com.koubotools: DEBUG